module.exports = Object.freeze({
  POLIZA_VER: 'POLIZA_VER',
  POLIZA_CREAR: 'POLIZA_CREAR',
  POLIZA_EDITAR: 'POLIZA_EDITAR',
  POLIZA_APROBAR: 'POLIZA_APROBAR',
  POLIZA_ANULAR: 'POLIZA_ANULAR',
  CUENTA_VER: 'CUENTA_VER',
  CUENTA_CREAR: 'CUENTA_CREAR',
  CUENTA_EDITAR: 'CUENTA_EDITAR',
  PERIODO_CERRAR: 'PERIODO_CERRAR',
  REPORTE_VER: 'REPORTE_VER',
  BITACORA_VER: 'BITACORA_VER',
});
